/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_bjhl_testjni_JniTest */

#ifndef _Included_com_example_bjhl_testjni_JniTest
#define _Included_com_example_bjhl_testjni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_bjhl_testjni_JniTest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_bjhl_testjni_JniTest_get
  (JNIEnv *, jobject);

/*
 * Class:     com_example_bjhl_testjni_JniTest
 * Method:    set_1
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_bjhl_testjni_JniTest_set_11
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
